- name: Ensure the required variables are defined
  ansible.builtin.assert:
    that:
      - etcd_initial_cluster_token is defined
      - etcd_cluster_group_name is defined
    fail_msg: One or more required variables are not defined. Check README for a list of variables.

- name: Install etcd server from package
  ansible.builtin.apt:
    name: etcd-server
    state: present

- name: Create etcd configuration directory
  ansible.builtin.file:
    path: /etc/etcd/
    owner: etcd
    group: etcd
    mode: '0700'
    state: directory

- name: Create etcd configuration directories
  ansible.builtin.file:
    path: /etc/etcd/tls
    owner: etcd
    group: etcd
    mode: '0700'
    state: directory

- name: Copy TLS certificates and keys
  with_items: "{{ etcd_upload_tls_certificates }}"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/etcd/tls/
    owner: 'etcd'
    group: 'etcd'
    mode: '400'


- name: Ensure the required TLS certificate and key files are present
  # The configuration template requires the files listed below:
  with_items:
    - /etc/etcd/tls/server-cert.pem
    - /etc/etcd/tls/server-key.pem
    - /etc/etcd/tls/peer-cert.pem
    - /etc/etcd/tls/peer-key.pem
    - /etc/etcd/tls/client-ca-cert.pem
    - /etc/etcd/tls/peer-ca-cert.pem
  ansible.builtin.file:
    path: "{{ item }}"
    state: file

- name: Configure etcd
  with_items:
    - filename: etcd
      destination_dir: /etc/default/
  ansible.builtin.template:
    src: '{{ item.filename }}.j2'
    dest: '{{ item.destination_dir }}/{{ item.filename }}'
    owner: 'etcd'
    group: 'etcd'
    mode: '640'
  notify:
    - Restart etcd